#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  >&2 echo "Usage: $(basename $0) <author> <commit>"
  exit 1
fi

AUTHOR=$1


COMMIT_HASH=$2
if [ "$2" = "--" ]; then
    COMMIT_HASH=HEAD
fi

AUTHOR_NAME=$(echo $AUTHOR | perl -wlne '/^([^<]+).*>$/ and print $1' | awk '{gsub(/^ +| +$/,"")} {print $0}')
AUTHOR_EMAIL=$(echo $AUTHOR | perl -wlne '/^.*\s*<(.*)>$/ and print $1' | awk '{gsub(/^ +| +$/,"")} {print $0}')
COMMIT=$(git rev-parse --short $COMMIT_HASH)

{
  GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/edit $COMMIT/'" git rebase -i $COMMIT~1^^
  GIT_COMMITTER_NAME="$AUTHOR_NAME" GIT_COMMITTER_EMAIL="$AUTHOR_EMAIL" git commit --amend --no-edit --author="$AUTHOR"
  git rebase --continue
} &> /dev/null

echo "$AUTHOR_NAME is now the author of $COMMIT. You're officially an asshole.";
